export const FETCH_WEATHER = "COMMAND/FETCH_WEATHER_FOR_LAT_LNG";
export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const WEATHER_ID_RECEIVED = "EVENT/WEATHER_ID_RECEIVED";
export const FETCH_DRONE = "COMMAND/FETCH_DRONE"; 
export const FETCH_MULTI_WEATHER = "COMMAND/FETCH_MULTI_WEATHER";
export const WEATHER_MULTI_ID_RECEIVED = "EVENT/WEATHER_MULTI_ID_RECEIVED";
export const WEATHER_MULTI_DATA_RECEIVED = "EVENT/WEATHER_MULTI_DATA_RECEIVED";
export const DRONE_DATA_RECEIVED = "EVENT/DRONE_DATA_RECEIVED";

